name: Run Build Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  build_tests:
    uses: OpenVoiceOS/gh-automations/.github/workflows/build-tests.yml@dev
    secrets: inherit
    with:
      system_deps: 'swig'
      test_path: "test/"
      package_name: "ovos-skill-confucius-quotes"
      entry_point: "ovos-skill-confucius-quotes.openvoiceos"
      plugin_type: "skill"
      pr_comment: true
      opm_section: true
      opm_validate_interface: true
      opm_test_import: true
      opm_perf_threshold_ms: 500
