name: Coverage Report
on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  coverage:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@dev
    secrets: inherit
    with:
      python_version: "3.11"
      system_deps: 'swig'
      coverage_source: "ovos_skill_confucius_quotes"
      min_coverage: 80
      install_extras: ".[test]"
      pr_comment: true
      publish_to_gh_pages: false
