name: Coverage Pages
on:
  push:
    branches: [dev]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  coverage_pages:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@dev
    secrets: inherit
    with:
      python_version: "3.11"
      system_deps: 'swig'
      coverage_source: "ovos_skill_confucius_quotes"
      pr_comment: false
      publish_to_gh_pages: true
