name: Downstream Dependency Check
on:
  push:
    branches: [dev, master]
  workflow_dispatch:

jobs:
  downstream_check:
    uses: OpenVoiceOS/gh-automations/.github/workflows/downstream-check.yml@dev
    secrets: inherit
    with:
      package_name: "ovos-skill-confucius-quotes"
