name: Python Support
on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  python_support:
    uses: OpenVoiceOS/gh-automations/.github/workflows/python-support.yml@dev
    secrets: inherit
    with:
      package_name: "ovos-skill-confucius-quotes"
      entry_point: "ovos-skill-confucius-quotes.openvoiceos"
