name: Release Alpha and Propose Stable

on:
  pull_request:
    types: [closed]
    branches: [dev]
  workflow_dispatch:

jobs:

  publish_alpha:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-alpha.yml@dev
    secrets: inherit
    with:
      branch: 'dev'
      version_file: 'version.py'
      update_changelog: true
      publish_prerelease: true
      propose_release: true
      publish_pypi: true
      notify_matrix: true
      skip_bot_prs: true
      changelog_max_issues: 100
      matrix_message_pool: |
        🧙 "The man who moves a mountain begins by carrying away small stones."
        📜 "It does not matter how slowly you go as long as you do not stop."
        🎯 "When it is obvious that goals cannot be reached, don't adjust the goals, adjust the action steps."
        🌱 "The green reed which bends in the wind is stronger than the mighty oak which breaks in a storm."
        🔥 "Our greatest glory is not in never falling, but in rising every time we fall."
        ⚖️ "Before you embark on a journey of revenge, dig two graves."
        💎 "Better a diamond with a flaw than a pebble without."
