name: Sync Translations
on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  sync_translations:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'gitlocalize-app[bot]'
    uses: OpenVoiceOS/gh-automations/.github/workflows/sync-translations.yml@dev
    secrets: inherit
    with:
      branch: dev
